#!/usr/bin/env bash

git_root=$(git rev-parse --show-toplevel)
error_msg=$(mktemp)
failures=0

if [[ -e /etc/profile.d/rvm.sh ]]; then
  source /etc/profile.d/rvm.sh
  rvm system 2>/dev/null
fi

cd $git_root

for file in $(git diff --cached --name-only --diff-filter=ACM); do
  if type puppet >/dev/null 2>&1; then
    if [[ $(echo $file | grep -q '\.*\.pp$'; echo $?) -eq 0 ]]; then
      puppet parser validate $file > $error_msg
      if [[ $? -ne 0 ]]; then
        failures=$((failures+1))
        cat $error_msg
        echo
        echo /dev/null > $error_msg
      fi
    fi

    if [[ $(echo $file | grep -q '\.*\.erb$'; echo $?) -eq 0 ]]; then
      erb -P -x -T '-' $file | ruby -c
      if [[ $? -ne 0 ]]; then
        failures=$((failures+1))
        cat $error_msg
        echo
        echo /dev/null > $error_msg
      fi
    fi
  fi

  if type ruby >/dev/null 2>&1; then
    if [[ $(head -n 1 $file | grep -q '#!/usr/bin/env ruby'; echo $?) -eq 0 ]]; then
      ruby -c $file
      if [[ $? -ne 0 ]]; then
        failures=$((failures+1))
        cat $error_msg
        echo
        echo /dev/null > $error_msg
      fi
    fi
  fi
done

if [[ $failures -ne 0 ]]; then
  echo "COMMIT ABORTED: $failures failures found" >&2
  exit 1
fi

if [[ -e $error_msg ]]; then
  rm $error_msg
fi

exit 0
